name = "my-telegram-bot"
#main = "src/index.js"
main = "hello.py"
compatibility_date = "2024-03-16"
compatibility_flags = ["python_workers"]

#[build]
#main = "hello.py"

# Uncomment and replace with your real secret variables if needed
[[vars]]
TELEGRAM_BOT_TOKEN = "7823854850:AAGwcumdHLpdZXdtlTMbO8Et4oH4CZLkQdE"
CHAT_ID = "314589754"

# KV Namespace (if you plan to store data)
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-namespace-id"

# Enable fetch event for handling API requests
workers_dev = true